name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            openjdk-17-jdk \
            zip \
            unzip \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev \
            python3-setuptools

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install --upgrade cython
          pip3 install buildozer kivy

      - name: Run Buildozer
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        run: |
          buildozer android debug
