name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer

      - name: Show Python and pip version
        run: |
          python --version
          pip --version

      - name: Run buildozer with debug
        run: |
          buildozer -v android debug
