name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show environment info
        run: |
          python --version
          pip --version
          uname -a
          env

      - name: List project files
        run: ls -al

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer

      - name: Run Buildozer (verbose)
        run: buildozer -v android debug
